baseURL = "https://www.adityakgupta.in/"
languageCode = "en-GB"
title = "Tech Talks"
theme = "rahul" # huge thanks to Rahul R. Nadkarni ;)
canonifyURLs = true

[markup]
  [markup.tableOfContents]
    endLevel = 6
    [markup.goldmark]
    [markup.goldmark.extensions]
        [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
            block = [['\[', '\]'], ['$$', '$$']]
            inline = [['\(', '\)']]

[taxonomies]
    tag = "tags"

[params]
    author = "Aditya Kumar Gupta"
    github = "https://github.com/adityakgupta"
    linkedin = "https://linkedin.com/in/aditya-kgupta"
    twitter = "https://x.com/aditya_kgupta"
    mainSections = ["posts"]
    description = "Things I read"
    designer = "https://rahulrn.framer.website/"
    image = "images/main.png"

[outputs]
home = ["HTML", "JSON", "RSS"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
